version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-stretch-node
      - image: postgres:9.5
        environment:
          POSTGRES_USER: acebook-loungin-lizards
          POSTGRES_DB: acebook-loungin-lizards_test
          POSTGRES_PASSWORD: ""
    executor: ruby/default
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: acebook-loungin-lizards-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: acebook-loungin-lizards-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: Which bundler?
          command: bundle -v

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake
